# Generated by Django 5.1.7 on 2025-03-17 04:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signer',
            fields=[
                ('signature_counters', models.AutoField(primary_key=True, serialize=False)),
                ('signer_full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('signer_father_name', models.CharField(blank=True, default='', max_length=255)),
                ('signer_mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('signer_birthdate', models.DateField()),
                ('signer_cpf', models.CharField(max_length=14, unique=True)),
                ('signer_id', models.CharField(max_length=14, unique=True)),
                ('signer_rg_number', models.CharField(blank=True, max_length=10, null=True)),
                ('signer_rg_issuing_authority', models.CharField(blank=True, max_length=10, null=True)),
                ('signer_email', models.EmailField(max_length=254)),
                ('signer_email_is_checked', models.BooleanField(default=False)),
                ('signer_mobile_number', models.CharField(default='+55 (37) 9 NNNN-NNNN', max_length=20)),
                ('signer_mobile_is_checked', models.BooleanField(default=False)),
                ('signer_social_network_ID', models.JSONField(choices=[('google', 'Google'), ('facebook', 'Facebook'), ('twitter', 'Twitter')], default=dict)),
                ('signer_signature_is_hidden', models.BooleanField(default=False)),
                ('signing_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('originating_ip', models.CharField(max_length=39)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('hash_and_time', models.CharField(max_length=255)),
                ('pin_code', models.CharField(blank=True, max_length=9, null=True)),
                ('email_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('mobile_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('signer_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('signer_signature', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Signer',
                'verbose_name_plural': 'Signers',
            },
        ),
    ]
