# Generated by Django 5.1.7 on 2025-03-15 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signer',
            name='signing_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
