# Generated by Django 5.1.7 on 2025-03-17 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referendo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signer',
            old_name='signature_counters',
            new_name='signature_counter',
        ),
    ]
