# Generated by Django 5.1.7 on 2025-03-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_signer_signing_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='signer',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
