# Generated by Django 5.1.7 on 2025-03-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_otp_signer_email_otp_signer_mobile_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signer',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='signer',
            name='pin_code',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='signer',
            name='signer_rg_issuing_authority',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='signer',
            name='signer_rg_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
